<?php

$search = array('<iframe src="//www.youtube.com/embed/OmLNs6zQIHo?rel=0" height="329" width="585" allowfullscreen="" frameborder="0"></iframe>', 
				'<iframe src="//www.youtube.com/embed/1ar5P_MNUuU" height="329" width="585" allowfullscreen="" frameborder="0"></iframe>', 
				'href="http://www.expeditie-ichthus.nl/expeditieleden/', 
				'/"', 
				'<iframe src="//www.youtube.com/embed/XtyQ8v8Nomg?rel=0" height="329" width="585" allowfullscreen="" frameborder="0"></iframe>',
				'[print_gllr id=466]',
				'[print_gllr id=821]',
				'[print_gllr id=793]',
				'[print_gllr id=682]',
				'[print_gllr id=643]',
				'[wpch_thermometer id="333" position="right"]',
				'href="http://www.expeditie-ichthus.nl/overig/',
				'<strong>',
				'<b>',
				'</strong>',
				'height="300" />',
				'height="225" />',
				'height="271" />',
				'height="200" />',
				'height="260" />',
				'<img class="alignright size-medium wp-image-251" style="font-size: 13px; line-height: 19.5px;" alt="Agatha van Ginkel" src="http://www.expeditie-ichthus.nl/wp-content/uploads/2013/10/Agatha-van-Ginkel-300x225.jpg" width="300" height="225" />',
				'Via deze pagina kunt u alle expeditieleden en hun motivatie afzonderlijk bekijken.<a href');
$replace = array('Bekijk het filmpje van Birdy, waar onze expeditie zijn naam aan heeft ontleend, op <a href="https://www.youtube.com/watch?v=OmLNs6zQIHo" target="_blank">YouTube</a>!', 
				'Bekijk ons promofilmpje op <a href="https://www.youtube.com/watch?v=1ar5P_MNUuU" target="_blank">YouTube</a>!', 
				'href="http://www.ichost.nl/124832/#', 
				'"', 
				'Bekijk het videoverslag van de sponsorloop op <a href="https://www.youtube.com/watch?v=XtyQ8v8Nomg" target="_blank">YouTube</a>!',
				'',
				'',
				'',
				'',
				'',
				'',
				'href="http://www.ichost.nl/124832/#',
				'</br></br><strong>',
				'</br><b>',
				'</strong></br>',
				'height="300" /></br>',
				'height="225" /></br>',
				'height="271" /></br>',
				'height="200" /></br>',
				'height="260" /></br>',
				'</br><img class="alignright size-medium wp-image-251" style="font-size: 13px; line-height: 19.5px;" alt="Agatha van Ginkel" src="http://www.expeditie-ichthus.nl/wp-content/uploads/2013/10/Agatha-van-Ginkel-300x225.jpg" width="300" height="225" />',
				'Via deze pagina kunt u alle expeditieleden en hun motivatie afzonderlijk bekijken.</br><a href');

?>